Partial-code-merge
- Added silhouette visualization for different numbers of cluster centers
- Condensed elbow visualization plots
- Merged and reorganzied our seperate codebases until cell block 11, where the following error is thrown:
"AttributeError: 'numpy.ndarray' object has no attribute 'Reset_index'"

The error seems to be related to a conflict between the numpy array modification you used in your code (add columns) and the way my code handles the data as a dataframe.

Seemingly relevant stackoverflow questions here:
https://datascience.stackexchange.com/questions/60770/multivariate-regression-error-attributeerror-numpy-ndarray-object-has-no-att

https://stackoverflow.com/questions/37624903/python-pandas-dataframe-attributeerror-numpy-ndarray-object-has-no-attribute

Shouldn't be a major roadblock, just need to look at it with some fresh eyes tomorrow.